///////////////////////////////////////////////////////////////////////
// BXF - Barlist Exchange File
// Copyright © 1999-2019  Washington State Department of Transportation
//                        Bridge and Structures Office
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the Alternate Route Open Source License as 
// published by the Washington State Department of Transportation, 
// Bridge and Structures Office.
//
// This program is distributed in the hope that it will be useful, but 
// distribution is AS IS, WITHOUT ANY WARRANTY; without even the implied 
// warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See 
// the Alternate Route Open Source License for more details.
//
// You should have received a copy of the Alternate Route Open Source 
// License along with this program; if not, write to the Washington 
// State Department of Transportation, Bridge and Structures Office, 
// P.O. Box  47340, Olympia, WA 98503, USA or e-mail 
// Bridge_Support@wsdot.wa.gov
///////////////////////////////////////////////////////////////////////

// BXF.idl : IDL source for BXF.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (Addin.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "BarlistAddin.idl";

[
	uuid(12FCFC87-1F41-11D3-8941-006097C68A9C),
	version(1.0),
	helpstring("BXF 1.0 Type Library")
]
library BXFLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(B026E9AF-CCE7-41D4-AFBF-E2DEF7528EDA),
		helpstring("BXFAddin Class")
	]
	coclass BXFAddin
	{
		[default] interface IBarlistAddin;
	};
};
