//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Barlist.rc
//
#define EAFID_INDICATOR_MIN             1
#define EAFID_INDICATOR_MODIFIED        1
#define EAFID_INDICATOR_STATUS          2
#define EAFID_INDICATOR_AUTOCALC_ON     3
#define EAFID_INDICATOR_AUTOCALC_OFF    4
#define EAFID_INDICATOR_MAX             4
#define EAF_TOOLBAR_MENU_COUNT          40
#define EAF_REPORT_MENU_COUNT           50
#define EAF_GRAPH_MENU_COUNT            50
#define IDS_PROJNAME                    100
#define IDR_BARLIST_10_TO_20_XSLT       101
#define IDR_PLUGIN                      102
#define IDR_BARLIST                     129
#define IDR_COLLABORATION               130
#define IDR_COMPONENTINFO               131
#define IDC_SI                          201
#define IDC_US                          202
#define IDC_INCREMENT                   203
#define IDR_TOOLBAR                     206
#define IDD_OPTIONS                     208
#define IDC_GROUPS                      209
#define IDC_STATUS                      211
#define IDD_BAR                         212
#define IDC_LOCATION                    212
#define IDC_MARK                        213
#define IDC_BAR_SIZE                    214
#define IDD_PROPERTIES                  214
#define IDI_RED                         215
#define IDC_NUM_REQUIRED                215
#define IDI_YELLOW                      216
#define IDC_LONGITUDINAL                216
#define IDI_GREEN                       217
#define IDC_TRANSVERSE                  217
#define IDC_SEISMIC                     218
#define IDI_HELP                        218
#define IDC_LUMP_SUM                    219
#define IDD_QUANTITIES                  219
#define IDC_SUBSTRUCTURE                220
#define IDC_EPOXY                       221
#define IDD_RENUMBER                    221
#define IDC_VARIES                      222
#define IDC_NUM_EACH                    223
#define IDR_TREE_CONTEXT                223
#define IDC_STATUS_MESSAGE              224
#define IDR_LIST_CONTEXT                224
#define IDC_TYPE                        225
#define IDD_REPORT                      225
#define IDC_DIMENSIONS_GROUP            226
#define IDC_U                           227
#define IDD_COLLABORATION_MANAGER       227
#define IDC_W                           228
#define IDC_X                           229
#define IDC_Y                           230
#define IDC_Z                           231
#define IDC_T1                          232
#define IDC_T2                          233
#define IDC_T1_LABEL                    234
#define IDC_T2_LABEL                    235
#define IDC_VARIES_U                    236
#define IDC_VARIES_W                    237
#define IDC_VARIES_X                    238
#define IDC_VARIES_Y                    239
#define IDC_VARIES_Z                    240
#define IDC_VARIES_T1_LABEL             241
#define IDC_VARIES_T1                   242
#define IDC_T2_VARIES_LABEL             243
#define IDC_VARIES_T2_LABEL             243
#define IDC_VARIES_T2                   244
#define IDC_UPDATE_BAR                  246
#define IDC_PROJECT_NAME                248
#define IDC_JOB_NUMBER                  249
#define IDC_ENGINEER                    250
#define IDC_COMPANY                     251
#define IDC_COMMENTS                    252
#define IDC_SAVE                        253
#define IDI_SAVE                        255
#define IDCHELP                         256
#define IDC_GROUP                       256
#define XSLTFILE                        256
#define IDC_SUBSTRUCTURE_EPOXY          258
#define IDC_SUPERSTRUCTURE              259
#define IDC_SUPERSTRUCTURE_EPOXY        260
#define IDC_FIRST                       261
#define IDC_HEADER                      263
#define IDC_REPORT                      264
#define IDC_PRINT                       265
#define IDI_PRINT                       266
#define IDC_BEND_GUIDE                  266
#define IDI_COLLABORATION               267
#define IDC_FILES                       267
#define IDC_REMOVE                      268
#define IDC_BUTTON3                     270
#define IDC_ADD                         271
#define IDC_BUTTON2                     272
#define IDC_QUANTITIES_LIST             273
#define IDC_COMBO1                      274
#define IDC_MATERIALS                   274
#define EAF_RESERVED_COMMAND_BASE       0x8000
#define EAFID_UNITS_SI                  32772
#define EAFID_UNITS_US                  32773
#define EAFID_HELP_SOURCE               32782
#define ID_NEW_VIEW                     33029
#define ID_VIEW_OPTIONS                 33032
#define IDC_MOVE_UP                     33035
#define IDC_MOVE_DOWN                   33036
#define IDC_DELETE                      33037
#define IDC_RENAME                      33038
#define ID_QNI                          33039
#define IDC_ADD_BAR                     33040
#define ID_ADD_GROUP                    33041
#define IDC_SELECT_ALL                  33042
#define ID_PLACEHOLDER                  33044
#define ID_PROPERTIES                   33045
#define FIRST_ADDIN_COMMAND             33046
#define LAST_ADDIN_COMMAND              33050
#define IDC_EDIT_CUT                    33054
#define IDC_QUANTITIES                  33060
#define ID_GENERATE_MARK_NUMBERS        33061
#define ID_DELETE                       33062
#define ID_EDIT_BAR                     33063
#define ID_VIEW_REPORT                  33064
#define IDC_FILE_PRINT                  33066
#define IDC_COLLABORATION_MANAGER       33067

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        229
#define _APS_NEXT_COMMAND_VALUE         33068
#define _APS_NEXT_CONTROL_VALUE         275
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
